package yekonga

var DefaultTenantDatabaseStructure DatabaseStructure = DatabaseStructure{
	"Tenants": map[string]CollectionFieldConfig{
		"id":              {Kind: "ID", DefaultValue: nil, Required: false},
		"userId":          {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"name":            {Kind: "String", DefaultValue: nil, Required: false},
		"description":     {Kind: "String", DefaultValue: nil, Required: false},
		"logoUrl":         {Kind: "URL", DefaultValue: nil, Required: false},
		"faviconUrl":      {Kind: "URL", DefaultValue: nil, Required: false},
		"type":            {Kind: "String", DefaultValue: "COMPANY", Required: false, Options: []string{"NGO", "COMPANY", "PRIVATE"}},
		"address":         {Kind: "String", DefaultValue: nil, Required: false},
		"email":           {Kind: "String", DefaultValue: nil, Required: false},
		"phone":           {Kind: "String", DefaultValue: nil, Required: false},
		"website":         {Kind: "String", DefaultValue: nil, Required: false},
		"domain":          {Kind: "String", DefaultValue: nil, Required: false, Index: true},
		"subdomain":       {Kind: "String", DefaultValue: nil, Required: false, Index: true},
		"customDomain":    {Kind: "String", DefaultValue: nil, Required: false, Index: true},
		"customSubdomain": {Kind: "String", DefaultValue: nil, Required: false, Index: true},
		"language":        {Kind: "String", DefaultValue: "en", Required: false},
		"isApproved":      {Kind: "Boolean", DefaultValue: false, Required: false},
		"status":          {Kind: "String", DefaultValue: "active", Required: false, Options: []string{"active", "inactive"}},
		"createdAt":       {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"TenantConfigs": map[string]CollectionFieldConfig{
		"id":                {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":          {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"lightTheme":        {Kind: "Any", DefaultValue: nil, Required: false},
		"darkTheme":         {Kind: "Any", DefaultValue: nil, Required: false},
		"defaultTheme":      {Kind: "String", DefaultValue: "lightTheme", Required: false},
		"smtp":              {Kind: "Any", DefaultValue: nil, Required: false},
		"sms":               {Kind: "Any", DefaultValue: nil, Required: false},
		"whatsapp":          {Kind: "Any", DefaultValue: nil, Required: false},
		"payment":           {Kind: "Any", DefaultValue: nil, Required: false}, // {"providers": [...]}, same shape as config apiGateway.payment; overrides the defaults per provider
		"publicCanRegister": {Kind: "Boolean", DefaultValue: false, Required: false},
		"hasMembership":     {Kind: "Boolean", DefaultValue: false, Required: false},
		"otherConfig":       {Kind: "Any", DefaultValue: nil, Required: false},
		"language":          {Kind: "String", DefaultValue: "en", Required: false},
	},
	"TenantFeatures": map[string]CollectionFieldConfig{
		"id":          {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"moduleName":  {Kind: "String", DefaultValue: nil, Required: false},
		"featureCode": {Kind: "String", DefaultValue: nil, Required: false},
		"enabled":     {Kind: "Boolean", DefaultValue: true, Required: false},
	},
	"TenantUsers": map[string]CollectionFieldConfig{
		"id":        {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":  {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"userId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"role":      {Kind: "String", DefaultValue: "public", Required: false, Options: []string{"admin", "public"}},
		"status":    {Kind: "String", DefaultValue: "active", Required: false, Options: []string{"active", "inactive"}},
		"createdAt": {Kind: "Date", DefaultValue: "now", Required: false},
	},
}

var DefaultTenantCatchDatabaseStructure DatabaseStructure = DatabaseStructure{
	"TenantCatches": map[string]CollectionFieldConfig{
		"id":       {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId": {Kind: "ID", DefaultValue: nil, Required: false, Index: true},
		"domain":   {Kind: "String", DefaultValue: nil, Required: false, Index: true},
	},
}

var DefaultAuthDatabaseStructure DatabaseStructure = DatabaseStructure{
	"Users": map[string]CollectionFieldConfig{
		"id":                 {Kind: "ID", DefaultValue: nil, Required: false},
		"firstName":          {Kind: "String", DefaultValue: nil, Required: false},
		"secondName":         {Kind: "String", DefaultValue: nil, Required: false},
		"lastName":           {Kind: "String", DefaultValue: nil, Required: false},
		"username":           {Kind: "String", DefaultValue: nil, Required: false, Protected: false, Index: true},
		"usernameType":       {Kind: "String", DefaultValue: nil, Required: false, Protected: false, Options: []string{"name", "email", "phone", "whatsapp"}},
		"email":              {Kind: "String", DefaultValue: nil, Required: false, Protected: false, Index: true},
		"phone":              {Kind: "String", DefaultValue: nil, Required: false, Protected: false, Index: true},
		"whatsapp":           {Kind: "String", DefaultValue: nil, Required: false, Protected: false, Index: true},
		"profileUrl":         {Kind: "URL", DefaultValue: nil, Required: false},
		"gender":             {Kind: "String", DefaultValue: nil, Required: false, Options: []string{"male", "female"}},
		"dateOfBirth":        {Kind: "Date", DefaultValue: nil, Required: false},
		"password":           {Kind: "String", DefaultValue: nil, Required: false, Protected: true},
		"role":               {Kind: "String", DefaultValue: nil, Required: false, Options: []string{"admin", "user"}},
		"token":              {Kind: "String", DefaultValue: nil, Required: false, Protected: true},
		"googleToken":        {Kind: "String", DefaultValue: nil, Required: false, Protected: true},
		"rememberToken":      {Kind: "String", DefaultValue: nil, Required: false, Protected: true},
		"deviceToken":        {Kind: "String", DefaultValue: nil, Required: false, Protected: true},
		"status":             {Kind: "String", DefaultValue: "active", Required: false, Options: []string{"active", "inactive"}},
		"isActive":           {Kind: "Boolean", DefaultValue: false, Required: false},
		"isBanned":           {Kind: "Boolean", DefaultValue: false, Required: false},
		"isPhoneVerified":    {Kind: "Boolean", DefaultValue: false, Required: false},
		"phoneVerifyCode":    {Kind: "String", DefaultValue: false, Required: false, Protected: true},
		"phoneVerifiedAt":    {Kind: "Date", DefaultValue: nil, Required: false},
		"isEmailVerified":    {Kind: "Boolean", DefaultValue: false, Required: false},
		"emailVerifyCode":    {Kind: "String", DefaultValue: false, Required: false, Protected: true},
		"emailVerifiedAt":    {Kind: "Date", DefaultValue: nil, Required: false},
		"isWhatsappVerified": {Kind: "Boolean", DefaultValue: false, Required: false},
		"whatsappVerifyCode": {Kind: "String", DefaultValue: false, Required: false, Protected: true},
		"whatsappVerifiedAt": {Kind: "Date", DefaultValue: nil, Required: false},
		"otpCode":            {Kind: "String", DefaultValue: nil, Required: false, Protected: true},
		"otpCreatedAt":       {Kind: "Date", DefaultValue: nil, Required: false},
		"userType":           {Kind: "String", DefaultValue: "individual", Required: false, Options: []string{"individual", "organization"}},
		"lastActive":         {Kind: "Date", DefaultValue: "now", Required: false},
		"createdAt":          {Kind: "Date", DefaultValue: "now", Required: false},
		"updatedAt":          {Kind: "Date", DefaultValue: "now", Required: false},
		"deletedAt":          {Kind: "Date", DefaultValue: nil, Required: false},
	},
	"UserVerifications": map[string]CollectionFieldConfig{
		"id":            {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":      {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"userId":        {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"username":      {Kind: "String", DefaultValue: nil, Required: false, Protected: true},
		"usernameType":  {Kind: "String", DefaultValue: nil, Required: false, Options: []string{"name", "email", "phone", "whatsapp"}},
		"target":        {Kind: "String", DefaultValue: nil, Required: false, Protected: true},
		"otpCode":       {Kind: "String", DefaultValue: nil, Required: false, Protected: true},
		"otpCreatedAt":  {Kind: "Date", DefaultValue: nil, Required: false, Protected: true},
		"otpVerifiedAt": {Kind: "Date", DefaultValue: nil, Required: false},
		"count":         {Kind: "Number", DefaultValue: 0, Required: false, Protected: true},
		"createdAt":     {Kind: "Date", DefaultValue: "now", Required: false},
		"updatedAt":     {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"Profiles": map[string]CollectionFieldConfig{
		"id":          {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"userId":      {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"name":        {Kind: "String", DefaultValue: nil, Required: false},
		"description": {Kind: "String", DefaultValue: nil, Required: false},
		"profileUrl":  {Kind: "URL", DefaultValue: nil, Required: false},
		"type":        {Kind: "String", DefaultValue: nil, Required: false, Options: []string{"admin", "manager", "user"}},
		"address":     {Kind: "String", DefaultValue: nil, Required: false},
		"email":       {Kind: "String", DefaultValue: nil, Required: false},
		"phone":       {Kind: "String", DefaultValue: nil, Required: false},
		"website":     {Kind: "String", DefaultValue: nil, Required: false},
		"domain":      {Kind: "String", DefaultValue: nil, Required: false},
		"subdomain":   {Kind: "String", DefaultValue: nil, Required: false},
		"language":    {Kind: "String", DefaultValue: "en", Required: false},
		"isPrivate":   {Kind: "Boolean", DefaultValue: false, Required: false},
		"isApproved":  {Kind: "Boolean", DefaultValue: false, Required: false},
		"status":      {Kind: "String", DefaultValue: "active", Required: false, Options: []string{"active", "inactive"}},
		"deletedAt":   {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"ProfileUsers": map[string]CollectionFieldConfig{
		"id":        {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":  {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"profileId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Profile", Key: "id"}},
		"userId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"role":      {Kind: "String", DefaultValue: nil, Required: false, Options: []string{"manager", "user"}},
		"status":    {Kind: "String", DefaultValue: "active", Required: false, Options: []string{"active", "inactive"}},
		"createdAt": {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"RefreshTokens": map[string]CollectionFieldConfig{
		"id":        {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":  {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"domain":    {Kind: "String", DefaultValue: nil, Required: false},
		"profileId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Profile", Key: "id"}},
		"userId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"adminId":   {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"tokenHash": {Kind: "String", DefaultValue: nil, Required: false, Protected: true},
		"userAgent": {Kind: "String", DefaultValue: nil, Required: false},
		"ipAddress": {Kind: "String", DefaultValue: nil, Required: false},
		"revoked":   {Kind: "Boolean", DefaultValue: false, Required: false},
		"expiresAt": {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"LoginAttempts": map[string]CollectionFieldConfig{
		"id":        {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":  {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"domain":    {Kind: "String", DefaultValue: nil, Required: false},
		"profileId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Profile", Key: "id"}},
		"userId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"username":  {Kind: "String", DefaultValue: "active", Required: false, Options: []string{"success", "fail"}},
		"status":    {Kind: "String", DefaultValue: "active", Required: false, Options: []string{"success", "fail"}},
		"timestamp": {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"UserDevices": map[string]CollectionFieldConfig{
		"id":         {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":   {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"userId":     {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"deviceUuid": {Kind: "String", DefaultValue: nil, Required: false},
		"type":       {Kind: "Any", DefaultValue: nil, Required: false},
		"info":       {Kind: "Any", DefaultValue: nil, Required: false},
		"status":     {Kind: "String", DefaultValue: "active", Required: false, Options: []string{"active", "inactive"}},
		"createdAt":  {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"UserDeviceCommands": map[string]CollectionFieldConfig{
		"id":           {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":     {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"userDeviceId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "UserDevice", Key: "id"}},
		"deviceUuid":   {Kind: "String", DefaultValue: nil, Required: false},
		"action":       {Kind: "String", DefaultValue: nil, Required: false},
		"type":         {Kind: "String", DefaultValue: "command", Required: false, Options: []string{"command", "notification", "chat"}},
		"isSent":       {Kind: "Boolean", DefaultValue: false, Required: false},
		"isReceived":   {Kind: "Boolean", DefaultValue: false, Required: false},
		"createdAt":    {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"AuthPermissions": map[string]CollectionFieldConfig{
		"id":          {Kind: "ID", DefaultValue: nil, Required: false},
		"moduleName":  {Kind: "String", DefaultValue: nil, Required: false},
		"group":       {Kind: "String", DefaultValue: nil, Required: false},
		"code":        {Kind: "String", DefaultValue: nil, Required: false},
		"name":        {Kind: "String", DefaultValue: nil, Required: false},
		"description": {Kind: "String", DefaultValue: nil, Required: false},
		"isVisible":   {Kind: "Boolean", DefaultValue: true, Required: false},
	},
	"AuthGroups": map[string]CollectionFieldConfig{
		"id":          {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"profileId":   {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Profile", Key: "id"}},
		"moduleName":  {Kind: "String", DefaultValue: nil, Required: false},
		"name":        {Kind: "String", DefaultValue: nil, Required: false},
		"description": {Kind: "String", DefaultValue: nil, Required: false},
	},
	"AuthGroupPermissions": map[string]CollectionFieldConfig{
		"id":               {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":         {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"authGroupId":      {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "AuthGroup", Key: "id"}},
		"authPermissionId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "AuthPermission", Key: "id"}},
	},
	"AuthUserPermissions": map[string]CollectionFieldConfig{
		"id":          {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"profileId":   {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Profile", Key: "id"}},
		"userId":      {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"authGroupId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "AuthGroup", Key: "id"}},
		"moduleName":  {Kind: "String", DefaultValue: nil, Required: false},
		"code":        {Kind: "String", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "AuthPermission", Key: "code"}},
	},
	"TranslatorLanguages": map[string]CollectionFieldConfig{
		"id":     {Kind: "ID", DefaultValue: nil, Required: false},
		"locale": {Kind: "String", DefaultValue: nil, Required: false},
		"name":   {Kind: "String", DefaultValue: nil, Required: false},
		"flag":   {Kind: "String", DefaultValue: nil, Required: false},
		"status": {Kind: "String", DefaultValue: "active", Required: false, Options: []string{"active", "inactive"}},
	},
	"TranslatorTranslations": map[string]CollectionFieldConfig{
		"id":                   {Kind: "ID", DefaultValue: nil, Required: false},
		"translatorLanguageId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "TranslatorLanguage", Key: "id"}},
		"locale":               {Kind: "String", DefaultValue: nil, Required: false},
		"moduleName":           {Kind: "String", DefaultValue: nil, Required: false},
		"group":                {Kind: "String", DefaultValue: nil, Required: false},
		"item":                 {Kind: "String", DefaultValue: nil, Required: false},
		"description":          {Kind: "String", DefaultValue: nil, Required: false},
		"text":                 {Kind: "String", DefaultValue: nil, Required: false},
		"unstable":             {Kind: "String", DefaultValue: nil, Required: false},
		"locked":               {Kind: "String", DefaultValue: nil, Required: false},
	},
	"Locations": map[string]CollectionFieldConfig{
		"id":        {Kind: "ID", DefaultValue: nil, Required: false},
		"parentId":  {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Location", Key: "id"}},
		"name":      {Kind: "String", DefaultValue: nil, Required: false},
		"shortCode": {Kind: "String", DefaultValue: nil, Required: false},
		"phoneCode": {Kind: "String", DefaultValue: nil, Required: false},
		"currency":  {Kind: "String", DefaultValue: nil, Required: false},
		"flag":      {Kind: "String", DefaultValue: nil, Required: false},
		"type":      {Kind: "String", DefaultValue: "region", Required: false, Options: []string{"country", "region", "district", "ward"}},
		"latitude":  {Kind: "Float", DefaultValue: nil, Required: false},
		"longitude": {Kind: "Float", DefaultValue: nil, Required: false},
	},
}

var DefaultBillingDatabaseStructure DatabaseStructure = DatabaseStructure{
	"Modules": map[string]CollectionFieldConfig{
		"id":          {Kind: "ID", DefaultValue: nil, Required: false},
		"moduleName":  {Kind: "String", DefaultValue: nil, Required: false},
		"title":       {Kind: "String", DefaultValue: nil, Required: false},
		"description": {Kind: "String", DefaultValue: nil, Required: false},
		"enabled":     {Kind: "Boolean", DefaultValue: true, Required: false},
	},
	"PricingPlans": map[string]CollectionFieldConfig{
		"id":           {Kind: "ID", DefaultValue: nil, Required: false},
		"moduleId":     {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Module", Key: "id"}},
		"pricingType":  {Kind: "String", DefaultValue: "flat", Required: false, Options: []string{"flat", "per_user", "per_unit", "metered"}},
		"billingCycle": {Kind: "String", DefaultValue: "flat", Required: false, Options: []string{"monthly", "yearly"}},
		"price":        {Kind: "Float", DefaultValue: 0, Required: false},
		"trialDays":    {Kind: "Number", DefaultValue: 30, Required: false},
		"graceDays":    {Kind: "Number", DefaultValue: 7, Required: false},
	},
	"Subscriptions": map[string]CollectionFieldConfig{
		"id":                 {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":           {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"status":             {Kind: "String", DefaultValue: "flat", Required: false, Options: []string{"active", "grace", "trailing", "past_due", "canceled", "unpaid", "expired"}},
		"trialStart":         {Kind: "Date", DefaultValue: nil, Required: false},
		"trialEnd":           {Kind: "Date", DefaultValue: nil, Required: false},
		"currentPeriodStart": {Kind: "Date", DefaultValue: nil, Required: false},
		"currentPeriodEnd":   {Kind: "Date", DefaultValue: nil, Required: false},
		"gracePeriodEnd":     {Kind: "Date", DefaultValue: nil, Required: false},
		"nextBillingDate":    {Kind: "Date", DefaultValue: nil, Required: false},
		"canceledAt":         {Kind: "Date", DefaultValue: nil, Required: false},
	},
	"SubscriptionItems": map[string]CollectionFieldConfig{
		"id":             {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":       {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"subscriptionId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Subscription", Key: "id"}},
		"moduleId":       {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Module", Key: "id"}},
		"pricingPlanId":  {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "PricingPlan", Key: "id"}},
		"quantity":       {Kind: "Float", DefaultValue: 0, Required: false},
	},
	"UsageRecords": map[string]CollectionFieldConfig{
		"id":          {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"moduleId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Module", Key: "id"}},
		"quantity":    {Kind: "Float", DefaultValue: 0, Required: false},
		"periodStart": {Kind: "Date", DefaultValue: nil, Required: false},
		"periodEnd":   {Kind: "Date", DefaultValue: nil, Required: false},
	},
	"Invoices": map[string]CollectionFieldConfig{
		"id":              {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":        {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"subscriptionId":  {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Subscription", Key: "id"}},
		"amountDue":       {Kind: "Float", DefaultValue: 0, Required: false},
		"amountPaid":      {Kind: "Float", DefaultValue: 0, Required: false},
		"amountRemaining": {Kind: "Float", DefaultValue: 0, Required: false},
		"status":          {Kind: "String", DefaultValue: "flat", Required: false, Options: []string{"paid", "pending", "partially_paid", "failed", "canceled"}},
		"dueDate":         {Kind: "Date", DefaultValue: nil, Required: false},
		"paidDate":        {Kind: "Date", DefaultValue: nil, Required: false},
	},
	"InvoiceItems": map[string]CollectionFieldConfig{
		"id":                 {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":           {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"invoiceId":          {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Invoice", Key: "id"}},
		"moduleId":           {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Module", Key: "id"}},
		"subscriptionItemId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "SubscriptionItem", Key: "id"}},
		"description":        {Kind: "String", DefaultValue: nil, Required: false},
		"pricingType":        {Kind: "String", DefaultValue: "flat", Required: false, Options: []string{"flat", "per_user", "per_unit", "metered"}},
		"quantity":           {Kind: "Float", DefaultValue: 0, Required: false},
		"unitPrice":          {Kind: "Float", DefaultValue: 0, Required: false},
		"totalPrice":         {Kind: "Float", DefaultValue: 0, Required: false},
		"currency":           {Kind: "String", DefaultValue: nil, Required: false},
		"startPeriod":        {Kind: "Date", DefaultValue: nil, Required: false},
		"endPeriod":          {Kind: "Date", DefaultValue: nil, Required: false},
		"metadata":           {Kind: "Any", DefaultValue: nil, Required: false},
		"createdAt":          {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"AccountCredits": map[string]CollectionFieldConfig{
		"id":        {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":  {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"paymentId": {Kind: "String", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Payments", Key: "id"}},
		"amount":    {Kind: "Float", DefaultValue: 0, Required: false},
		"createdAt": {Kind: "Date", DefaultValue: "now", Required: false},
	},
}

var DefaultPaymentDatabaseStructure DatabaseStructure = DatabaseStructure{

	"Payments": map[string]CollectionFieldConfig{
		"id":                {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":          {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"provider":          {Kind: "String", DefaultValue: nil, Required: false},
		"providerConfig":    {Kind: "String", DefaultValue: "default", Required: false, Options: []string{"default", "tenant"}}, // whose gateway account the payment runs on
		"providerReference": {Kind: "String", DefaultValue: nil, Required: false},
		"providerPaymentId": {Kind: "String", DefaultValue: nil, Required: false},
		"checkoutUrl":       {Kind: "String", DefaultValue: nil, Required: false},
		"amount":            {Kind: "Float", DefaultValue: 0, Required: false},
		"charge":            {Kind: "Float", DefaultValue: nil},
		"currency":          {Kind: "String", DefaultValue: "TZS"},

		"tillNumber":       {Kind: "String", DefaultValue: nil},
		"txnDate":          {Kind: "String", DefaultValue: nil},
		"txnId":            {Kind: "String", DefaultValue: nil},
		"txnAmount":        {Kind: "Float", DefaultValue: nil},
		"txnPhone":         {Kind: "String", DefaultValue: nil},
		"paymentReference": {Kind: "String", DefaultValue: nil},
		"channel":          {Kind: "String", DefaultValue: nil, Options: []string{"vodacom", "tigo", "airtel", "halotel", "ttcl", "zantel", "mobile_money", "card", "bank_transfer", "paypal", "qr", "cash", "manual"}},
		"method":           {Kind: "String", DefaultValue: nil, Options: []string{"system", "selcom", "clickpesa", "azampay", "flutterwave", "pesapal", "stripe", "paypal", "2checkout", "manual", "cash"}},
		"paymentTagId":     {Kind: "ID", DefaultValue: nil},
		"reference":        {Kind: "String", DefaultValue: nil},
		"transactionData":  {Kind: "Any", DefaultValue: nil},
		// Gateway payments use pending/succeeded/failed/refunded (the framework's
		// payment webhook writes these); SUCCESS/PENDING/FAIL are kept for
		// manual/cash entries.
		"status":        {Kind: "String", DefaultValue: nil, Options: []string{"PENDING", "SUCCESS", "FAILED", "CANCELED", "REFUNDED"}},
		"paymentMethod": {Kind: "String", DefaultValue: nil, Options: []string{"manual", "card", "bank_transfer", "mobile_money", "paypal", "crypto"}},
		"failureReason": {Kind: "String", DefaultValue: nil},
		"paidAt":        {Kind: "Date", DefaultValue: nil},
		"refundedAt":    {Kind: "Date", DefaultValue: nil},
		"metadata":      {Kind: "Any", DefaultValue: nil},
		"message":       {Kind: "String", DefaultValue: nil},
		"isPaid":        {Kind: "Boolean", DefaultValue: false},
		"createdBy":     {Kind: "ID", DefaultValue: nil},
		"updatedAt":     {Kind: "Date", DefaultValue: "now", Required: false},
		"createdAt":     {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"PaymentProviderRequests": map[string]CollectionFieldConfig{
		"id":                {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":          {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"paymentId":         {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Payment", Key: "id"}},
		"provider":          {Kind: "String", DefaultValue: nil, Required: false},
		"action":            {Kind: "String", DefaultValue: nil, Required: false, Options: []string{"createPayment"}},
		"reference":         {Kind: "String", DefaultValue: nil, Required: false},
		"providerReference": {Kind: "String", DefaultValue: nil, Required: false},
		"status":            {Kind: "String", DefaultValue: nil, Required: false, Options: []string{"succeeded", "failed"}},
		"httpStatus":        {Kind: "Integer", DefaultValue: nil, Required: false},
		"errorCode":         {Kind: "String", DefaultValue: nil, Required: false},
		"errorMessage":      {Kind: "String", DefaultValue: nil, Required: false},
		"request":           {Kind: "Any", DefaultValue: nil, Required: false},
		"response":          {Kind: "Any", DefaultValue: nil, Required: false},
		"durationMs":        {Kind: "Integer", DefaultValue: 0, Required: false},
		"createdAt":         {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"PaymentAllocations": map[string]CollectionFieldConfig{
		"id":              {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":        {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"paymentId":       {Kind: "String", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Payments", Key: "id"}},
		"invoiceId":       {Kind: "String", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Invoice", Key: "id"}},
		"amountAllocated": {Kind: "Float", DefaultValue: 0, Required: false},
		"createdAt":       {Kind: "Date", DefaultValue: "now", Required: false},
	},
}

var DefaultExtraDatabaseStructure DatabaseStructure = DatabaseStructure{
	"Notifications": map[string]CollectionFieldConfig{
		"id":                {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":          {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"profileId":         {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Profile", Key: "id"}},
		"userId":            {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"senderName":        {Kind: "String", DefaultValue: nil, Required: false},
		"referenceId":       {Kind: "ID", DefaultValue: nil, Required: false},
		"referenceName":     {Kind: "String", DefaultValue: nil, Required: false},
		"recipient":         {Kind: "String", DefaultValue: nil, Required: false},
		"recipientName":     {Kind: "String", DefaultValue: nil, Required: false},
		"replyTo":           {Kind: "String", DefaultValue: nil, Required: false},
		"title":             {Kind: "String", DefaultValue: nil, Required: false},
		"content":           {Kind: "Any", DefaultValue: nil, Required: false},
		"link":              {Kind: "String", DefaultValue: nil, Required: false},
		"attachment":        {Kind: "String", DefaultValue: nil, Required: false},
		"trackingCode":      {Kind: "String", DefaultValue: nil, Required: false},
		"type":              {Kind: "String", DefaultValue: nil, Required: false, Options: []string{"mail", "sms", "push"}},
		"isSeen":            {Kind: "Boolean", DefaultValue: false, Required: false},
		"status":            {Kind: "String", DefaultValue: nil, Required: false, Options: []string{"submitted", "waiting", "delivered", "undelivered"}},
		"response":          {Kind: "Any", DefaultValue: nil, Required: false},
		"responseReference": {Kind: "String", DefaultValue: nil, Required: false},
		"timestamp":         {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"PushNotifications": map[string]CollectionFieldConfig{
		"id":             {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":       {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"profileId":      {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Profile", Key: "id"}},
		"userId":         {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"deviceId":       {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "UserDevice", Key: "id"}},
		"title":          {Kind: "String", DefaultValue: nil, Required: false},
		"body":           {Kind: "String", DefaultValue: nil, Required: false},
		"iconUrl":        {Kind: "URL", DefaultValue: nil, Required: false},
		"pictureUrl":     {Kind: "URL", DefaultValue: nil, Required: false},
		"payload":        {Kind: "String", DefaultValue: nil, Required: false},
		"action":         {Kind: "String", DefaultValue: nil, Required: false},
		"actionTargetId": {Kind: "Any", DefaultValue: nil, Required: false},
		"isDelivered":    {Kind: "Boolean", DefaultValue: nil, Required: false},
		"status":         {Kind: "String", DefaultValue: nil, Required: false, Options: []string{"waiting", "sent", "delivered"}},
		"createdAt":      {Kind: "Date", DefaultValue: "now", Required: false},
		"updatedAt":      {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"SocketMessages": map[string]CollectionFieldConfig{
		"id":        {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":  {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"profileId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Profile", Key: "id"}},
		"userId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"deviceId":  {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "UserDevice", Key: "id"}},
		"namespace": {Kind: "String", DefaultValue: nil, Required: false},
		"action":    {Kind: "String", DefaultValue: nil, Required: false},
		"content":   {Kind: "Any", DefaultValue: nil, Required: false},
		"status":    {Kind: "String", DefaultValue: nil, Required: false, Options: []string{"waiting", "sent", "delivered"}},
		"createdAt": {Kind: "Date", DefaultValue: "now", Required: false},
		"updatedAt": {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"AuditTrails": map[string]CollectionFieldConfig{
		"id":         {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":   {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"profileId":  {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Profile", Key: "id"}},
		"userId":     {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"action":     {Kind: "String", DefaultValue: nil, Required: false},
		"documentId": {Kind: "ID", DefaultValue: nil, Required: false},
		"collection": {Kind: "String", DefaultValue: nil, Required: false},
		"model":      {Kind: "String", DefaultValue: nil, Required: false},
		"newValues":  {Kind: "Any", DefaultValue: nil, Required: false},
		"oldValues":  {Kind: "Any", DefaultValue: nil, Required: false},
		"ipAddress":  {Kind: "String", DefaultValue: nil, Required: false},
		"browser":    {Kind: "Any", DefaultValue: nil, Required: false},
		"userAgent":  {Kind: "String", DefaultValue: nil, Required: false},
		"createdAt":  {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"IpAccessRules": map[string]CollectionFieldConfig{
		"id":        {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":  {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"ipAddress": {Kind: "String", DefaultValue: nil, Required: true},
		"type":      {Kind: "String", DefaultValue: "blacklist", Required: false, Options: []string{"whitelist", "blacklist"}},
		"reason":    {Kind: "String", DefaultValue: nil, Required: false},
		"source":    {Kind: "String", DefaultValue: "manual", Required: false, Options: []string{"manual", "errorGuard"}},
		// Snapshot of the request that tripped an errorGuard block, kept for
		// investigation — which endpoint was being hit, and with what.
		"url":       {Kind: "String", DefaultValue: nil, Required: false},
		"method":    {Kind: "String", DefaultValue: nil, Required: false},
		"headers":   {Kind: "Any", DefaultValue: nil, Required: false},
		"body":      {Kind: "Any", DefaultValue: nil, Required: false},
		"expiresAt": {Kind: "Date", DefaultValue: nil, Required: false}, // null = permanent
		"createdAt": {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"Reports": map[string]CollectionFieldConfig{
		"id":          {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"userId":      {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"profileId":   {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Profile", Key: "id"}},
		"name":        {Kind: "String", DefaultValue: nil, Required: false},
		"description": {Kind: "String", DefaultValue: nil, Required: false},
		"data":        {Kind: "Any", DefaultValue: nil, Required: false},
		"isPrivate":   {Kind: "Boolean", DefaultValue: nil, Required: false},
		"isDashboard": {Kind: "Boolean", DefaultValue: nil, Required: false},
		"sendEmail":   {Kind: "Boolean", DefaultValue: nil, Required: false},
		"emails":      {Kind: "Any", DefaultValue: nil, Required: false},
		"createdAt":   {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"ChatGroups": map[string]CollectionFieldConfig{
		"id":              {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":        {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"profileId":       {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Profile", Key: "id"}},
		"parentReference": {Kind: "ID", DefaultValue: nil, Required: false},
		"reference":       {Kind: "ID", DefaultValue: nil, Required: false},
		"title":           {Kind: "String", DefaultValue: nil, Required: false},
		"description":     {Kind: "String", DefaultValue: nil, Required: false},
		"members":         {Kind: "{ID}", DefaultValue: []string{}, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "ChatGroupMember"}},
		"type":            {Kind: "String", DefaultValue: "public", Required: false, Options: []string{"private", "public", "general"}},
		"timestamp":       {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"ChatGroupMembers": map[string]CollectionFieldConfig{
		"id":              {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":        {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"reference":       {Kind: "ID", DefaultValue: nil, Required: false},
		"userId":          {Kind: "ID", DefaultValue: nil, Required: false},
		"userReferenceId": {Kind: "ID", DefaultValue: nil, Required: false},
		"name":            {Kind: "String", DefaultValue: nil, Required: false},
		"profileUrl":      {Kind: "String", DefaultValue: nil, Required: false},
		"isAdmin":         {Kind: "Boolean", DefaultValue: false, Required: false},
		"isOwner":         {Kind: "Boolean", DefaultValue: false, Required: false},
		"timestamp":       {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"ChatMessages": map[string]CollectionFieldConfig{
		"id":                {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":          {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"chatGroupId":       {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "ChatGroup"}},
		"chatGroupMemberId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "ChatGroupMember", Key: "id"}},
		"content":           {Kind: "String", DefaultValue: nil, Required: false},
		"media":             {Kind: "Any", DefaultValue: nil, Required: false},
		"mediaReference":    {Kind: "String", DefaultValue: nil, Required: false},
		"type":              {Kind: "String", DefaultValue: "active", Required: false, Options: []string{"text", "image", "location", "document", "video", "audio"}},
		"timestamp":         {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"ChatMessageStates": map[string]CollectionFieldConfig{
		"id":                {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":          {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"chatMessageId":     {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "ChatMessage", Key: "id"}},
		"chatGroupMemberId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "ChatGroupMember", Key: "id"}},
		"sent":              {Kind: "Boolean", DefaultValue: false, Required: false},
		"sentDate":          {Kind: "Date", DefaultValue: nil, Required: false},
		"received":          {Kind: "Boolean", DefaultValue: false, Required: false},
		"receivedDate":      {Kind: "Date", DefaultValue: nil, Required: false},
		"opened":            {Kind: "Boolean", DefaultValue: false, Required: false},
		"openedDate":        {Kind: "Date", DefaultValue: nil, Required: false},
		"timestamp":         {Kind: "Date", DefaultValue: "now", Required: false},
	},

	"CustomForms": {
		"id":                 {Kind: "ID"},
		"tenantId":           {Kind: "ID", DefaultValue: nil, Required: false},
		"parentCustomFormId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "CustomForms", Key: "id"}},
		"entity":             {Kind: "String", Options: []string{"order", "customer", "outlet"}},
		"position":           {Kind: "Integer", DefaultValue: 0, Required: false},
		"uniqueKey":          {Kind: "String", DefaultValue: nil, Required: false},
		"name":               {Kind: "String", DefaultValue: nil, Required: false},
		"label":              {Kind: "String", DefaultValue: nil, Required: false},
		"placeholder":        {Kind: "String", DefaultValue: nil, Required: false},
		"input":              {Kind: "String", DefaultValue: "text", Required: false, Options: []string{"title", "sub-title", "group", "text", "rating", "ranking", "words", "select", "textarea", "switch", "choice", "checkbox", "radio", "colorPicker", "datePicker", "file", "email", "phone", "password", "location"}},
		"type":               {Kind: "String", DefaultValue: "text", Required: false, Options: []string{"text", "number", "boolean"}},
		"isMandatory":        {Kind: "Boolean", DefaultValue: false, Required: false},
		"isMultiple":         {Kind: "Boolean", DefaultValue: false, Required: false},
		"isPublicHidden":     {Kind: "Boolean", DefaultValue: false, Required: false},
		"isRandomized":       {Kind: "Boolean", DefaultValue: false},
		"advancedOptions":    {Kind: "Boolean", DefaultValue: false, Required: false},
		"minimum":            {Kind: "Integer", DefaultValue: nil, Required: false},
		"maximum":            {Kind: "Integer", DefaultValue: nil, Required: false},
		"minimumLabel":       {Kind: "String", DefaultValue: nil},
		"maximumLabel":       {Kind: "String", DefaultValue: nil},

		"imageUrl":            {Kind: "URL", DefaultValue: nil},
		"hasImageUrl":         {Kind: "Boolean", DefaultValue: false},
		"icon":                {Kind: "String", DefaultValue: nil},
		"timer":               {Kind: "Number", DefaultValue: -1},
		"correctAnswerId":     {Kind: "ID", DefaultValue: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "survey_question_options", Key: "id"}},
		"isLive":              {Kind: "Boolean", DefaultValue: false},
		"hideResult":          {Kind: "Boolean", DefaultValue: false},
		"hasProfanityFilter":  {Kind: "Boolean", DefaultValue: false},
		"resultsAsPieChart":   {Kind: "Boolean", DefaultValue: false},
		"showRespondentNames": {Kind: "Boolean", DefaultValue: false},
		"mode":                {Kind: "String", DefaultValue: nil, Options: []string{"star", "emoji"}},
		"reportType":          {Kind: "String", DefaultValue: "pie", Options: []string{"pie", "rating", "ranking", "words"}},

		"descriptionMessage": {Kind: "String", DefaultValue: nil, Required: false},
		"errorMessage":       {Kind: "String", DefaultValue: nil, Required: false},
		"widthClass":         {Kind: "String", DefaultValue: nil, Required: false},
		"customClass":        {Kind: "String", DefaultValue: nil, Required: false},
		"options":            {Kind: "Any", DefaultValue: nil, Required: false},
		"hasCondition":       {Kind: "Boolean", DefaultValue: false, Required: false},
		"conditions":         {Kind: "Array", DefaultValue: []interface{}{}, Required: false},
		"status":             {Kind: "String", DefaultValue: "active", Required: false, Options: []string{"active", "inactive"}},
		"createdAt":          {Kind: "Datetime", DefaultValue: "now"},
		"updatedAt":          {Kind: "Datetime", DefaultValue: "now", Required: false},
	},
	"CustomFormOptions": {
		"id":           {Kind: "ID"},
		"tenantId":     {Kind: "ID", DefaultValue: nil, Required: false},
		"customFormId": {Kind: "ID", ForeignKey: CollectionFieldConfigForeignKey{Model: "CustomForms", Key: "id"}},
		"value":        {Kind: "String", DefaultValue: nil, Required: false},
		"name":         {Kind: "String", DefaultValue: nil, Required: false},
		"label":        {Kind: "String", DefaultValue: nil, Required: false},
		"correctValue": {Kind: "Boolean", DefaultValue: false},
		"position":     {Kind: "Integer", DefaultValue: 0, Required: false},
		"hasCondition": {Kind: "Boolean", DefaultValue: false, Required: false},
		"conditions":   {Kind: "Array", DefaultValue: []interface{}{}, Required: false},
		"status":       {Kind: "String", DefaultValue: "active", Options: []string{"active", "inactive"}},
	},
	"EnabledCustomForms": {
		"id":             {Kind: "ID"},
		"tenantId":       {Kind: "ID", DefaultValue: nil, Required: false},
		"customFormId":   {Kind: "ID", ForeignKey: CollectionFieldConfigForeignKey{Model: "CustomForms", Key: "id"}},
		"isPublicHidden": {Kind: "Boolean", DefaultValue: false, Required: false},
		"isMandatory":    {Kind: "Boolean", DefaultValue: false, Required: false},
		"position":       {Kind: "Integer", DefaultValue: 0, Required: false},
		"createdAt":      {Kind: "Datetime", DefaultValue: "now"},
	},
	"CustomFormSubmissions": {
		"id":        {Kind: "ID"},
		"tenantId":  {Kind: "ID", DefaultValue: nil, Required: false},
		"userId":    {Kind: "ID", DefaultValue: nil, Required: false},
		"createdAt": {Kind: "Datetime", DefaultValue: "now"},
		"updatedAt": {Kind: "Datetime", DefaultValue: "now", Required: false},
	},
	"CustomFormValues": {
		"id":                     {Kind: "ID"},
		"tenantId":               {Kind: "ID", DefaultValue: nil, Required: false},
		"userId":                 {Kind: "ID", DefaultValue: nil},
		"customFormSubmissionId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "CustomFormSubmissions", Key: "id"}},
		"customFormId":           {Kind: "ID", ForeignKey: CollectionFieldConfigForeignKey{Model: "CustomForms", Key: "id"}},
		"customFormOptionId":     {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "CustomFormOptions", Key: "id"}},
		"value":                  {Kind: "Any", DefaultValue: nil, Required: false},
		"isAnonymous":            {Kind: "Boolean", DefaultValue: false},
		"correct":                {Kind: "Boolean", DefaultValue: false},
		"time":                   {Kind: "Number", DefaultValue: nil},
		"createdAt":              {Kind: "Datetime", DefaultValue: "now"},
	},
}
