//! Go-compatible JSON decoding for the config files.
//!
//! Go's `encoding/json` matches object keys to struct fields
//! case-insensitively and leaves a field at its zero value when the JSON holds
//! `null` or the wrong type. Existing `config.json` files rely on both (the
//! README spells `connectionId` where the struct tag says `connectionID`), so
//! structs declared with [`go_json_struct!`] decode the same way:
//!
//! * keys match fields ignoring case and underscores (`baseURL`, `baseUrl`
//!   and `base_url` all fill `base_url`);
//! * `null` or a value of the wrong type leaves the field at its default,
//!   after trying the obvious string <-> number/bool conversions (so
//!   `"port": 5432` fills a string field, and `"server": "8080"` a number).

use serde::de::DeserializeOwned;
use serde::{Deserialize, Deserializer};
use serde_json::Value;

/// `deserialize_with` target: decodes any JSON value into `T`, falling back
/// to `T::default()` instead of failing.
pub fn or_default<'de, D, T>(deserializer: D) -> Result<T, D::Error>
where
    D: Deserializer<'de>,
    T: DeserializeOwned + Default,
{
    let value = Value::deserialize(deserializer)?;
    Ok(coerce(value))
}

/// Converts a JSON value into `T` the way Go would fill a struct field.
pub fn coerce<T: DeserializeOwned + Default>(value: Value) -> T {
    if let Ok(v) = T::deserialize(&value) {
        return v;
    }

    let converted = match &value {
        Value::String(s) => serde_json::from_str::<T>(s.trim()).ok(),
        Value::Number(_) | Value::Bool(_) => T::deserialize(Value::String(value.to_string())).ok(),
        _ => None,
    };

    converted.unwrap_or_default()
}

/// Key normalization used to match JSON keys to field names.
pub fn normalize_key(key: &str) -> String {
    key.chars()
        .filter(|c| *c != '_')
        .flat_map(char::to_lowercase)
        .collect()
}

/// Declares a config struct that decodes like a Go struct (see the module
/// docs) and serializes with camelCase keys.
macro_rules! go_json_struct {
    (
        $(#[$meta:meta])*
        pub struct $name:ident {
            $(
                $(#[$fmeta:meta])*
                pub $field:ident : $ty:ty
            ),* $(,)?
        }
    ) => {
        $(#[$meta])*
        #[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
        #[serde(remote = "Self", rename_all(serialize = "camelCase"))]
        pub struct $name {
            $(
                $(#[$fmeta])*
                #[serde(default, deserialize_with = "crate::helper::lenient::or_default")]
                pub $field: $ty,
            )*
        }

        impl<'de> serde::Deserialize<'de> for $name {
            fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
                use crate::helper::lenient::normalize_key;

                let value = serde_json::Value::deserialize(deserializer)?;
                let serde_json::Value::Object(object) = value else {
                    return Ok(Self::default());
                };

                let fields: &[&str] = &[$(stringify!($field)),*];
                let mut mapped = serde_json::Map::new();
                for (key, value) in object {
                    let wanted = normalize_key(&key);
                    if let Some(field) = fields.iter().find(|f| normalize_key(f) == wanted) {
                        mapped.insert((*field).to_string(), value);
                    }
                }

                // Resolves to the inherent fn generated by `remote = "Self"`.
                $name::deserialize(serde_json::Value::Object(mapped)).map_err(serde::de::Error::custom)
            }
        }

        impl serde::Serialize for $name {
            fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
                $name::serialize(self, serializer)
            }
        }
    };
}

pub(crate) use go_json_struct;

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    go_json_struct! {
        pub struct Inner {
            pub port: String,
            pub server: i64,
        }
    }

    go_json_struct! {
        pub struct Outer {
            #[serde(rename(serialize = "baseURL"))]
            pub base_url: String,
            pub connection_id: String,
            pub enabled: bool,
            pub list: Vec<String>,
            pub inner: Inner,
            pub free: Value,
        }
    }

    #[test]
    fn decodes_like_go() {
        let outer: Outer = serde_json::from_value(json!({
            "BASEURL": "/v1",
            "connectionId": "abc",
            "enabled": null,
            "list": "not a list",
            "inner": {"Port": 5432, "server": "8080"},
            "free": {"KeepCase": 1},
            "unknown": true
        }))
        .unwrap();

        assert_eq!(outer.base_url, "/v1");
        assert_eq!(outer.connection_id, "abc");
        assert!(!outer.enabled);
        assert!(outer.list.is_empty());
        assert_eq!(outer.inner.port, "5432");
        assert_eq!(outer.inner.server, 8080);
        assert_eq!(outer.free, json!({"KeepCase": 1}));

        let out = serde_json::to_value(&outer).unwrap();
        assert_eq!(out["baseURL"], "/v1");
        assert_eq!(out["connectionId"], "abc");
    }

    #[test]
    fn non_object_is_default() {
        let outer: Outer = serde_json::from_value(json!(null)).unwrap();
        assert_eq!(outer, Outer::default());
    }
}
